version: "3"

volumes:
  database:
    driver: local

services:
  mysql:
    platform: linux/amd64
    image: mariadb
    container_name: sah_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sah
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - database:/var/lib/mysql
